# Generated by Django 6.0 on 2026-01-04 03:52

import accounts.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_agentprofile_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackageFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('icon', models.CharField(blank=True, help_text='Icon emoji or class name', max_length=50)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Package Feature',
                'verbose_name_plural': 'Package Features',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Package title (e.g., PARIS)', max_length=200)),
                ('location', models.CharField(help_text='Location name (e.g., Paris)', max_length=200)),
                ('country', models.CharField(help_text='Country name (e.g., France)', max_length=100)),
                ('description', models.TextField(help_text='Detailed description of the package')),
                ('price_per_person', models.DecimalField(decimal_places=2, help_text='Price in Rs.', max_digits=10)),
                ('duration_days', models.PositiveIntegerField(default=7, help_text='Number of days')),
                ('duration_nights', models.PositiveIntegerField(default=6, help_text='Number of nights')),
                ('main_image', models.ImageField(blank=True, null=True, upload_to=accounts.models.package_image_path)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('draft', 'Draft')], default='active', max_length=20)),
                ('rating', models.DecimalField(decimal_places=1, default=0.0, help_text='Average rating (0-5)', max_digits=3)),
                ('participants_count', models.PositiveIntegerField(default=0, help_text='Number of people who joined')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(limit_choices_to={'role': 'agent'}, on_delete=django.db.models.deletion.CASCADE, related_name='packages', to=settings.AUTH_USER_MODEL)),
                ('features', models.ManyToManyField(blank=True, related_name='packages', to='accounts.packagefeature')),
            ],
            options={
                'verbose_name': 'Package',
                'verbose_name_plural': 'Packages',
                'ordering': ['-created_at'],
            },
        ),
    ]
