# Generated by Django 6.0 on 2026-01-29 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_packagefeature_package'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agentprofile',
            name='address',
        ),
        migrations.RemoveField(
            model_name='agentprofile',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='agentprofile',
            name='city',
        ),
        migrations.RemoveField(
            model_name='agentprofile',
            name='company_name',
        ),
        migrations.RemoveField(
            model_name='agentprofile',
            name='country',
        ),
        migrations.RemoveField(
            model_name='agentprofile',
            name='license_number',
        ),
        migrations.RemoveField(
            model_name='agentprofile',
            name='profile_picture',
        ),
        migrations.RemoveField(
            model_name='agentprofile',
            name='website',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='address',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='city',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='country',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='profile_picture',
        ),
        migrations.AddField(
            model_name='agentprofile',
            name='location',
            field=models.CharField(blank=True, help_text='Agent location', max_length=200),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='location',
            field=models.CharField(blank=True, help_text='User location', max_length=200),
        ),
    ]
