# Generated by Django 6.0 on 2026-01-29 07:46

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_agentprofile_address_remove_agentprofile_bio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to=accounts.models.agent_profile_image_path),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to=accounts.models.user_profile_image_path),
        ),
    ]
