# Generated by Django 6.0 on 2026-01-30 16:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='rating',
        ),
        migrations.AddField(
            model_name='agentprofile',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=0.0, help_text='Average rating from travelers (0-5)', max_digits=3),
        ),
        migrations.CreateModel(
            name='AgentReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveIntegerField(help_text='Rating from 1 to 5')),
                ('comment', models.TextField(blank=True, help_text='Review comment')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(limit_choices_to={'role': 'agent'}, on_delete=django.db.models.deletion.CASCADE, related_name='reviews_received', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(limit_choices_to={'role': 'traveler'}, on_delete=django.db.models.deletion.CASCADE, related_name='agent_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Agent Review',
                'verbose_name_plural': 'Agent Reviews',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'agent')},
            },
        ),
        migrations.DeleteModel(
            name='Review',
        ),
    ]
