# Generated by Django 6.0 on 2026-02-17 16:05

import accounts.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_chat_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='custompackage',
            name='claimed_at',
            field=models.DateTimeField(blank=True, help_text='When an agent first claimed this custom package', null=True),
        ),
        migrations.AddField(
            model_name='custompackage',
            name='claimed_by',
            field=models.ForeignKey(blank=True, help_text='Agent who claimed / is handling this custom package', limit_choices_to={'role': 'agent'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='claimed_custom_packages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='custompackage',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('claimed', 'Claimed'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='open', help_text='Lifecycle status for this custom package', max_length=20),
        ),
        migrations.AlterField(
            model_name='custompackage',
            name='main_image',
            field=models.ImageField(blank=True, null=True, upload_to=accounts.models.custom_package_image_path),
        ),
    ]
