# Generated by Django

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_custompackage_claimed_at_custompackage_claimed_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='custom_package',
            field=models.ForeignKey(
                blank=True,
                help_text='When set, this message is about this custom package (show package card + message).',
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='chat_messages',
                to='accounts.custompackage',
            ),
        ),
    ]
