# Generated by Django

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0014_chatmessage_custom_package"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="payment_method",
            field=models.CharField(
                choices=[("esewa", "eSewa"), ("direct", "Direct")],
                default="direct",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="payment_reference",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="booking",
            name="payment_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("paid", "Paid"),
                    ("failed", "Failed"),
                    ("refunded", "Refunded"),
                ],
                default="paid",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="price_per_person_snapshot",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="booking",
            name="total_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name="booking",
            name="transaction_uuid",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="booking",
            name="traveler_count",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.CreateModel(
            name="EsewaPaymentSession",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("transaction_uuid", models.CharField(max_length=120, unique=True)),
                ("traveler_count", models.PositiveIntegerField(default=1)),
                ("price_per_person_snapshot", models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ("total_amount", models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ("product_code", models.CharField(default="EPAYTEST", max_length=80)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("initiated", "Initiated"),
                            ("success_redirected", "Success Redirected"),
                            ("failed_redirected", "Failed Redirected"),
                            ("verified", "Verified"),
                            ("verify_failed", "Verify Failed"),
                        ],
                        default="initiated",
                        max_length=32,
                    ),
                ),
                ("payment_reference", models.CharField(blank=True, max_length=120)),
                ("esewa_status", models.CharField(blank=True, max_length=40)),
                ("verification_payload", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "booking",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="esewa_payment_session",
                        to="accounts.booking",
                    ),
                ),
                (
                    "package",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="esewa_payment_sessions",
                        to="accounts.package",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        limit_choices_to={"role": "traveler"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="esewa_payment_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "eSewa Payment Session",
                "verbose_name_plural": "eSewa Payment Sessions",
                "ordering": ["-created_at"],
            },
        ),
    ]
