# Generated by Django

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0015_booking_payment_fields_and_esewapaymentsession"),
    ]

    operations = [
        migrations.CreateModel(
            name="PackageBookmark",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "package",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bookmarks",
                        to="accounts.package",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        limit_choices_to={"role": "traveler"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="package_bookmarks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Package Bookmark",
                "verbose_name_plural": "Package Bookmarks",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="packagebookmark",
            constraint=models.UniqueConstraint(fields=("user", "package"), name="unique_traveler_package_bookmark"),
        ),
    ]
