# Generated by Django 6.0.3 on 2026-03-28 17:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0028_manual_refund_qr_and_requests'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='discount_percent',
            field=models.PositiveIntegerField(help_text='Discount percentage 1-99, e.g. 20 for 20% off', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(99)]),
        ),
    ]
