# Generated by Django 6.0.3 on 2026-03-29 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0029_alter_deal_discount_percent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='text',
            field=models.TextField(blank=True, default='', help_text='Caption; may be empty when an attachment is sent.'),
        ),
    ]
