# Generated by Django 6.0.3 on 2026-04-06 11:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0030_chatmessage_text_blank'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='trip_start_time',
            field=models.TimeField(blank=True, help_text='Planned trip start time in TIME_ZONE (used for 24h/1h reminders). Defaults to 09:00 if not set.', null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('alert', 'Alert'), ('emergency', 'Emergency'), ('rule_violation', 'Rule Violation'), ('info', 'Information'), ('update', 'Update'), ('promotion', 'Promotion'), ('general', 'General'), ('trip_reminder_24h', 'Trip reminder (24h)'), ('trip_reminder_1h', 'Trip reminder (1h)'), ('trip_review_request', 'Trip review request')], default='general', help_text='Type of notification - determines icon shown to user.', max_length=32),
        ),
        migrations.CreateModel(
            name='BookingTripReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('h24', '24 hours before trip'), ('h1', '1 hour before trip'), ('review', 'Post-trip review prompt')], max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trip_reminder_logs', to='accounts.booking')),
            ],
            options={
                'verbose_name': 'Booking trip reminder',
                'verbose_name_plural': 'Booking trip reminders',
                'unique_together': {('booking', 'kind')},
            },
        ),
    ]
