# Generated by Django 6.0.3 on 2026-04-06 18:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0031_trip_reminders_and_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='private_offer_for_user',
            field=models.ForeignKey(blank=True, help_text='If set, only this traveler can book; hidden from public package list.', limit_choices_to={'role': 'traveler'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='private_offer_packages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='package',
            name='source_custom_package',
            field=models.OneToOneField(blank=True, help_text='When set, this package was published from a traveler custom request.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='published_package', to='accounts.custompackage'),
        ),
    ]
