# Generated by Django 6.0.3 on 2026-04-07 03:28

import secrets

from django.db import migrations, models
from django.db.models import Q


def _random_code():
    return "".join(secrets.choice("0123456789") for _ in range(5))


def backfill_booking_codes(apps, schema_editor):
    Booking = apps.get_model("accounts", "Booking")
    existing = set(
        Booking.objects.exclude(booking_code__isnull=True)
        .exclude(booking_code="")
        .values_list("booking_code", flat=True)
    )
    for booking in Booking.objects.filter(
        Q(booking_code__isnull=True) | Q(booking_code="")
    ).order_by("pk"):
        for _ in range(1000):
            code = _random_code()
            if code not in existing and not Booking.objects.filter(booking_code=code).exists():
                booking.booking_code = code
                booking.save(update_fields=["booking_code"])
                existing.add(code)
                break
        else:
            raise RuntimeError("Could not assign unique booking_code during migration")


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0032_package_custom_publish_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="booking_code",
            field=models.CharField(
                blank=True,
                db_index=True,
                editable=False,
                help_text="Public 5-digit code (0-9, repeatable). Unique per booking for lookup and filtering.",
                max_length=5,
                null=True,
                unique=True,
            ),
        ),
        migrations.RunPython(backfill_booking_codes, noop_reverse),
        migrations.AlterField(
            model_name="booking",
            name="booking_code",
            field=models.CharField(
                db_index=True,
                editable=False,
                help_text="Public 5-digit code (0-9, repeatable). Unique per booking for lookup and filtering.",
                max_length=5,
                unique=True,
            ),
        ),
    ]
