# Generated by Django 6.0.3 on 2026-04-07 09:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0033_booking_booking_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='itinerarytrip',
            name='booking',
            field=models.ForeignKey(blank=True, help_text='Optional linked booking for richer PDF details.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='itinerary_trips', to='accounts.booking'),
        ),
        migrations.CreateModel(
            name='ItineraryActivityPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_name', models.CharField(max_length=220)),
                ('activity_timing', models.CharField(blank=True, max_length=120)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('entry_tickets_included', models.BooleanField(default=False)),
                ('guide_available', models.BooleanField(default=False)),
                ('prebooked', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('display_order', models.PositiveSmallIntegerField(default=1)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_plans', to='accounts.itinerarytrip')),
            ],
            options={
                'verbose_name': 'Itinerary Activity Plan',
                'verbose_name_plural': 'Itinerary Activity Plans',
                'ordering': ['display_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ItineraryCarryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, max_length=100)),
                ('item_name', models.CharField(max_length=220)),
                ('display_order', models.PositiveSmallIntegerField(default=1)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carry_items', to='accounts.itinerarytrip')),
            ],
            options={
                'verbose_name': 'Itinerary Carry Item',
                'verbose_name_plural': 'Itinerary Carry Items',
                'ordering': ['display_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ItineraryDocumentItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(blank=True, max_length=100)),
                ('document_name', models.CharField(max_length=220)),
                ('included', models.BooleanField(default=True)),
                ('notes', models.CharField(blank=True, max_length=220)),
                ('display_order', models.PositiveSmallIntegerField(default=1)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_items', to='accounts.itinerarytrip')),
            ],
            options={
                'verbose_name': 'Itinerary Document Item',
                'verbose_name_plural': 'Itinerary Document Items',
                'ordering': ['display_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ItineraryHotelStay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotel_name', models.CharField(max_length=180)),
                ('full_address', models.CharField(blank=True, max_length=320)),
                ('contact_number', models.CharField(blank=True, max_length=30)),
                ('check_in_time', models.CharField(blank=True, max_length=40)),
                ('check_out_time', models.CharField(blank=True, max_length=40)),
                ('room_type', models.CharField(blank=True, max_length=120)),
                ('amenities', models.TextField(blank=True)),
                ('display_order', models.PositiveSmallIntegerField(default=1)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotel_stays', to='accounts.itinerarytrip')),
            ],
            options={
                'verbose_name': 'Itinerary Hotel Stay',
                'verbose_name_plural': 'Itinerary Hotel Stays',
                'ordering': ['display_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ItineraryTransportSegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('segment_type', models.CharField(choices=[('home_pickup', 'Home Pickup'), ('main_travel', 'Main Travel'), ('arrival_transfer', 'Arrival Transfer')], max_length=30)),
                ('transport_type', models.CharField(blank=True, choices=[('flight', 'Flight'), ('bus', 'Bus'), ('train', 'Train'), ('car', 'Car'), ('van', 'Van'), ('other', 'Other')], max_length=30)),
                ('pickup_time', models.CharField(blank=True, max_length=40)),
                ('pickup_location', models.CharField(blank=True, max_length=300)),
                ('departure_time', models.CharField(blank=True, max_length=40)),
                ('departure_location', models.CharField(blank=True, max_length=300)),
                ('arrival_time', models.CharField(blank=True, max_length=40)),
                ('arrival_location', models.CharField(blank=True, max_length=300)),
                ('operator_name', models.CharField(blank=True, max_length=120)),
                ('operator_contact', models.CharField(blank=True, max_length=30)),
                ('vehicle_type', models.CharField(blank=True, max_length=120)),
                ('ticket_details', models.CharField(blank=True, max_length=180)),
                ('baggage_allowance', models.CharField(blank=True, max_length=120)),
                ('transfer_travel_time', models.CharField(blank=True, max_length=80)),
                ('display_order', models.PositiveSmallIntegerField(default=1)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transport_segments', to='accounts.itinerarytrip')),
            ],
            options={
                'verbose_name': 'Itinerary Transport Segment',
                'verbose_name_plural': 'Itinerary Transport Segments',
                'ordering': ['display_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ItineraryTripProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('traveler_full_names', models.CharField(blank=True, max_length=300)),
                ('traveler_contact_number', models.CharField(blank=True, max_length=30)),
                ('traveler_email', models.EmailField(blank=True, max_length=254)),
                ('booking_reference', models.CharField(blank=True, max_length=80)),
                ('travelers_adults', models.PositiveSmallIntegerField(default=1)),
                ('travelers_children', models.PositiveSmallIntegerField(default=0)),
                ('package_name', models.CharField(blank=True, max_length=220)),
                ('destinations', models.CharField(blank=True, max_length=400)),
                ('travel_type', models.CharField(blank=True, choices=[('luxury', 'Luxury'), ('budget', 'Budget'), ('adventure', 'Adventure'), ('family', 'Family'), ('business', 'Business'), ('other', 'Other')], max_length=24)),
                ('trip_highlights', models.TextField(blank=True)),
                ('weather_information', models.TextField(blank=True)),
                ('time_zone', models.CharField(blank=True, max_length=80)),
                ('meal_breakfast', models.CharField(blank=True, default='Included', max_length=40)),
                ('meal_lunch', models.CharField(blank=True, default='Included', max_length=40)),
                ('meal_dinner', models.CharField(blank=True, default='Included', max_length=40)),
                ('meal_locations', models.TextField(blank=True)),
                ('meal_preferences', models.CharField(blank=True, max_length=140)),
                ('important_instructions', models.TextField(blank=True)),
                ('support_agent_name', models.CharField(blank=True, max_length=140)),
                ('support_contact_number', models.CharField(blank=True, max_length=30)),
                ('support_email', models.EmailField(blank=True, max_length=254)),
                ('total_package_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('amount_paid', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('remaining_balance', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('payment_method', models.CharField(blank=True, max_length=60)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('trip', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='accounts.itinerarytrip')),
            ],
            options={
                'verbose_name': 'Itinerary Trip Profile',
                'verbose_name_plural': 'Itinerary Trip Profiles',
            },
        ),
    ]
