# Generated by Django 6.0.3 on 2026-04-08 08:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0036_itineraryhotelstay_stay_dates'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingAdminActionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('force_cancel', 'Force cancel'), ('internal_note', 'Internal note')], max_length=32)),
                ('reason', models.TextField(blank=True)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('admin', models.ForeignKey(blank=True, limit_choices_to={'role': 'admin'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booking_admin_actions', to=settings.AUTH_USER_MODEL)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_action_logs', to='accounts.booking')),
            ],
            options={
                'verbose_name': 'Booking admin action log',
                'verbose_name_plural': 'Booking admin action logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
