# Generated by Django 6.0.3 on 2026-04-08 08:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0037_bookingadminactionlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentReviewAdminActionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('delete_review', 'Delete review'), ('internal_note', 'Internal note')], max_length=32)),
                ('reason', models.TextField(blank=True)),
                ('note', models.TextField(blank=True)),
                ('reviewer_email_snapshot', models.EmailField(blank=True, max_length=254)),
                ('agent_email_snapshot', models.EmailField(blank=True, max_length=254)),
                ('rating_snapshot', models.PositiveIntegerField(default=0)),
                ('comment_snapshot', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('admin', models.ForeignKey(blank=True, limit_choices_to={'role': 'admin'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_review_admin_actions', to=settings.AUTH_USER_MODEL)),
                ('review', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_action_logs', to='accounts.agentreview')),
            ],
            options={
                'verbose_name': 'Agent review admin action log',
                'verbose_name_plural': 'Agent review admin action logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
