# Generated by Django 6.0.3 on 2026-04-08 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0038_agentreviewadminactionlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='agent_type',
            field=models.CharField(choices=[('regular', 'Regular'), ('guide', 'Guide')], default='regular', max_length=20),
        ),
        migrations.AddField(
            model_name='esewapaymentsession',
            name='agent_type',
            field=models.CharField(choices=[('regular', 'Regular'), ('guide', 'Guide')], default='regular', max_length=20),
        ),
    ]
