from django.urls import path

from .views import (
    LoginView,
    LogoutView,
    MeView,
    RefreshView,
    RegisterView,
    LeaderboardView,
    ProfileView,
    UserProfileView,
    AgentProfileView,
    PublicAgentDetailView,
    PackageListView,
    PackageDetailView,
    TravelerBookmarkListCreateView,
    TravelerBookmarkDeleteView,
    BookingListCreateView,
    BookingDetailView,
    EsewaPaymentInitiateView,
    EsewaPaymentCheckoutView,
    EsewaPaymentSuccessCallbackView,
    EsewaPaymentFailureCallbackView,
    EsewaPaymentVerifyView,
    AgentReviewListCreateView,
    CustomPackageListCreateView,
    CustomPackageDetailView,
    CustomPackageClaimAndChatView,
    PackageFeatureListView,
    ChatRoomListCreateView,
    ChatMessageListCreateView,
    ChatUnreadCountView,
    ChatRoomMarkReadView,
    ChatItineraryListCreateView,
    ChatItineraryDetailView,
    ChatItineraryTripCreateView,
    ChatItineraryTripPdfView,
    ChatItineraryTripSendView,
    NotificationListCreateView,
    NotificationUnreadCountView,
    NotificationMarkReadView,
    ExpoPushTokenRegisterView,
)

urlpatterns = [
    path("register/", RegisterView.as_view(), name="register"),
    path("login/", LoginView.as_view(), name="token_obtain_pair"),
    path("logout/", LogoutView.as_view(), name="logout"),
    path("refresh/", RefreshView.as_view(), name="token_refresh"),
    path("me/", MeView.as_view(), name="me"),
    # Profile endpoints
    path("profile/", ProfileView.as_view(), name="profile"),
    path("leaderboard/", LeaderboardView.as_view(), name="leaderboard"),
    path("profile/user/", UserProfileView.as_view(), name="user_profile"),
    path("profile/agent/", AgentProfileView.as_view(), name="agent_profile"),
    # Package endpoints
    path("packages/", PackageListView.as_view(), name="package_list"),
    path("packages/<int:id>/", PackageDetailView.as_view(), name="package_detail"),
    path("bookmarks/", TravelerBookmarkListCreateView.as_view(), name="traveler_bookmark_list_create"),
    path("bookmarks/<int:package_id>/", TravelerBookmarkDeleteView.as_view(), name="traveler_bookmark_delete"),
    # Agent review endpoints (travelers review agents after completing a trip)
    path("agents/<int:agent_id>/profile/", PublicAgentDetailView.as_view(), name="public_agent_detail"),
    path("agents/<int:agent_id>/reviews/", AgentReviewListCreateView.as_view(), name="agent_review_list_create"),
    # Booking endpoints
    path("bookings/", BookingListCreateView.as_view(), name="booking_list_create"),
    path("bookings/<int:pk>/", BookingDetailView.as_view(), name="booking_detail"),
    path("payments/esewa/initiate/", EsewaPaymentInitiateView.as_view(), name="esewa_payment_initiate"),
    path("payments/esewa/checkout/<str:transaction_uuid>/", EsewaPaymentCheckoutView.as_view(), name="esewa_payment_checkout"),
    path("payments/esewa/callback/success/", EsewaPaymentSuccessCallbackView.as_view(), name="esewa_payment_success_callback"),
    path("payments/esewa/callback/failure/", EsewaPaymentFailureCallbackView.as_view(), name="esewa_payment_failure_callback"),
    path("payments/esewa/verify/", EsewaPaymentVerifyView.as_view(), name="esewa_payment_verify"),
    # Custom packages (traveler-created; only visible to owner)
    path("custom-packages/", CustomPackageListCreateView.as_view(), name="custom_package_list_create"),
    path("custom-packages/<int:pk>/", CustomPackageDetailView.as_view(), name="custom_package_detail"),
    path(
        "custom-packages/<int:pk>/claim-and-chat/",
        CustomPackageClaimAndChatView.as_view(),
        name="custom_package_claim_and_chat",
    ),
    # Features list (for custom package / agent forms)
    path("features/", PackageFeatureListView.as_view(), name="package_feature_list"),
    # Chat
    path("chat/rooms/", ChatRoomListCreateView.as_view(), name="chat_room_list_create"),
    path("chat/rooms/<int:room_id>/messages/", ChatMessageListCreateView.as_view(), name="chat_message_list_create"),
    path("chat/rooms/<int:room_id>/itinerary/", ChatItineraryListCreateView.as_view(), name="chat_itinerary_list_create"),
    path("chat/rooms/<int:room_id>/itinerary/<int:pk>/", ChatItineraryDetailView.as_view(), name="chat_itinerary_detail"),
    path("chat/rooms/<int:room_id>/itinerary-trip/", ChatItineraryTripCreateView.as_view(), name="chat_itinerary_trip_create"),
    path("chat/rooms/<int:room_id>/itinerary-trip/<int:trip_id>/pdf/", ChatItineraryTripPdfView.as_view(), name="chat_itinerary_trip_pdf"),
    path("chat/rooms/<int:room_id>/itinerary-trip/<int:trip_id>/send/", ChatItineraryTripSendView.as_view(), name="chat_itinerary_trip_send"),
    path("chat/unread-count/", ChatUnreadCountView.as_view(), name="chat_unread_count"),
    path("chat/rooms/<int:room_id>/mark-read/", ChatRoomMarkReadView.as_view(), name="chat_room_mark_read"),
    # Notifications
    path("notifications/", NotificationListCreateView.as_view(), name="notification_list_create"),
    path("notifications/expo-token/", ExpoPushTokenRegisterView.as_view(), name="expo_push_token_register"),
    path("notifications/unread-count/", NotificationUnreadCountView.as_view(), name="notification_unread_count"),
    path("notifications/mark-read/<int:recipient_id>/", NotificationMarkReadView.as_view(), name="notification_mark_read"),
    path("notifications/mark-read/", NotificationMarkReadView.as_view(), name="notification_mark_read_post"),
]
