"""
Django settings for TRIPLINK project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from datetime import timedelta
from pathlib import Path
import os
from urllib.parse import urlparse

import dj_database_url
from decouple import Csv, config
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables from .env file (optional; decouple also reads .env)
load_dotenv(BASE_DIR / '.env')


# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config(
    'SECRET_KEY',
    default=config(
        'DJANGO_SECRET_KEY',
        default='django-insecure-@je^iql=!%9rtv2e_vj4yt%5(vl!(vde7f*)tp9^(^$(=5nn#k',
    ),
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=config('DJANGO_DEBUG', default='False'), cast=bool)

ALLOWED_HOSTS = [
    h
    for h in dict.fromkeys(
        [
            *config(
                'ALLOWED_HOSTS',
                default='localhost,127.0.0.1,192.168.18.6,10.148.97.183',
                cast=Csv(),
            ),
            *config('ALLOWED_HOSTS_EXTRA', default='', cast=Csv()),
        ]
    )
    if h
]
# Note: use hostname/IP only (no :port). The Host header is e.g. 10.219.151.183:8000 but ALLOWED_HOSTS matches the host part.

# Required for CSRF when accessing the site by IP or non-localhost (Django 4.0+)
CSRF_TRUSTED_ORIGINS = [
    'http://10.219.151.183:8000',
    'http://192.168.42.4:8000',
    'http://10.214.6.183:8000',
    'http://192.168.18.6:8000',
    'http://192.168.1.102:8000',
    'http://192.168.1.112:8000',
    'http://localhost:8000',
    'http://127.0.0.1:8000',
    'http://10.0.2.2:8000',
    'http://10.52.7.183:8000',
    'http://192.168.40.62:8000',
    'http://192.168.47.30:8000',
] + [x for x in config('CSRF_TRUSTED_ORIGINS_EXTRA', default='', cast=Csv()) if x]

# Render.com: trust HTTPS origin and Host (set in dashboard if auto env is missing)
_render_url = os.environ.get("RENDER_EXTERNAL_URL", "").strip().rstrip("/")
if not _render_url:
    _rh = os.environ.get("RENDER_EXTERNAL_HOSTNAME", "").strip()
    if _rh:
        _render_url = f"https://{_rh}"
if _render_url:
    _host = urlparse(_render_url).hostname
    if _host and _host not in ALLOWED_HOSTS:
        ALLOWED_HOSTS.append(_host)
    if _render_url not in CSRF_TRUSTED_ORIGINS:
        CSRF_TRUSTED_ORIGINS = list(CSRF_TRUSTED_ORIGINS) + [_render_url]

# Ensure CSRF cookie is sent on same-origin requests (default; explicit for clarity)
CSRF_COOKIE_SAMESITE = 'Lax'

CORS_ALLOW_ALL_ORIGINS = True

# Security (HTTPS termination on Render uses X-Forwarded-Proto)
SECURE_CONTENT_TYPE_NOSNIFF = True
if not DEBUG:
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    # So request.build_absolute_uri() uses the public host (e.g. *.onrender.com), not internal host
    USE_X_FORWARDED_HOST = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True

# Application definition

INSTALLED_APPS = [
    'daphne',  # Must be first for ASGI/WebSocket support
    'corsheaders',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework_simplejwt',
    'channels',
    'accounts',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'TRIPLINK.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.template.context_processors.csrf',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'TRIPLINK.wsgi.application'
ASGI_APPLICATION = 'TRIPLINK.asgi.application'

# Channel layers for WebSocket (in-memory for dev; use Redis in production)
CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels.layers.InMemoryChannelLayer',
    },
}


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

if config('DATABASE_URL', default=''):
    DATABASES = {
        'default': dj_database_url.config(
            default=config('DATABASE_URL'),
            conn_max_age=600,
            ssl_require=config('DATABASE_SSL_REQUIRE', default=True, cast=bool),
        ),
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.environ.get('DB_NAME', 'triplink_db'),
            'USER': os.environ.get('DB_USER', 'Rohan'),
            'PASSWORD': os.environ.get('DB_PASSWORD', ''),
            'HOST': os.environ.get('DB_HOST', 'localhost'),
            'PORT': os.environ.get('DB_PORT', '5432'),
        }
    }



# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [BASE_DIR / 'static']
STATIC_ROOT = BASE_DIR / 'staticfiles'

STORAGES = {
    'default': {
        'BACKEND': 'django.core.files.storage.FileSystemStorage',
    },
    'staticfiles': {
        'BACKEND': 'whitenoise.storage.CompressedManifestStaticFilesStorage',
    },
}

# Media files (user uploads)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

AUTH_USER_MODEL = 'accounts.User'

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
}

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=30),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=30),
    'AUTH_HEADER_TYPES': ('Bearer',),
    'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),
}

# Email configuration
# Supports both EMAIL_* and SMTP_* env names.
# In production, transactional email must use SMTP (not console backend).
EMAIL_HOST = config('EMAIL_HOST', default=config('SMTP_HOST', default='')).strip()
EMAIL_PORT = config('EMAIL_PORT', default=config('SMTP_PORT', default=587), cast=int)
EMAIL_USE_TLS = config('EMAIL_USE_TLS', default=config('SMTP_USE_TLS', default=True), cast=bool)
EMAIL_USE_SSL = config('EMAIL_USE_SSL', default=config('SMTP_USE_SSL', default=False), cast=bool)
EMAIL_HOST_USER = config('EMAIL_HOST_USER', default=config('SMTP_USER', default='')).strip()
EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD', default=config('SMTP_PASSWORD', default='')).strip()

if EMAIL_HOST:
    EMAIL_BACKEND = config(
        'EMAIL_BACKEND',
        default='django.core.mail.backends.smtp.EmailBackend',
    )
else:
    EMAIL_BACKEND = config(
        'EMAIL_BACKEND',
        default='django.core.mail.backends.console.EmailBackend',
    )

# Shown as "From:" — if not explicitly set, fallback to SMTP username.
DEFAULT_FROM_EMAIL = config(
    'DEFAULT_FROM_EMAIL',
    default=(EMAIL_HOST_USER or 'webmaster@localhost'),
).strip()
EMAIL_TIMEOUT = config('EMAIL_TIMEOUT', default=20, cast=int)


# Optional branding / copy for transactional email bodies
EMAIL_APP_NAME = os.environ.get('EMAIL_APP_NAME', 'TRIPLINK')
EMAIL_COMPANY_NAME = os.environ.get('EMAIL_COMPANY_NAME', 'TRIPLINK')
EMAIL_SUPPORT_ADDRESS = os.environ.get('EMAIL_SUPPORT_ADDRESS', '')
EMAIL_SYSTEM_NAME = os.environ.get('EMAIL_SYSTEM_NAME', 'TRIPLINK')
EMAIL_CONTACT_INFORMATION = os.environ.get('EMAIL_CONTACT_INFORMATION', '')

# OTP for traveler app password reset (API); use Redis cache in multi-instance production.
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'triplink-default-cache',
    }
}

# eSewa (UAT defaults; override in .env for production/live credentials)
ESEWA_PRODUCT_CODE = os.environ.get('ESEWA_PRODUCT_CODE', 'EPAYTEST')
ESEWA_SECRET_KEY = os.environ.get('ESEWA_SECRET_KEY', '8gBm/:&EnhH.1/q')
ESEWA_FORM_URL = os.environ.get('ESEWA_FORM_URL', 'https://rc-epay.esewa.com.np/api/epay/main/v2/form')
ESEWA_STATUS_URL = os.environ.get('ESEWA_STATUS_URL', 'https://rc.esewa.com.np/api/epay/transaction/status/')
# Optional: eSewa merchant refund endpoint (JSON POST). Obtain the exact URL and contract from eSewa for your merchant account.
ESEWA_REFUND_URL = os.environ.get('ESEWA_REFUND_URL', '')
ESEWA_REFUND_TIMEOUT = int(os.environ.get('ESEWA_REFUND_TIMEOUT', '30'))
